In [1]:
import pandas as pd

In [2]:
data = pd.read_csv(r"C:\Users\navee\Downloads\bank.csv")
data.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,59,admin.,married,secondary,no,2343,yes,no,unknown,5,may,1042,1,-1,0,unknown,yes
1,56,admin.,married,secondary,no,45,no,no,unknown,5,may,1467,1,-1,0,unknown,yes
2,41,technician,married,secondary,no,1270,yes,no,unknown,5,may,1389,1,-1,0,unknown,yes
3,55,services,married,secondary,no,2476,yes,no,unknown,5,may,579,1,-1,0,unknown,yes
4,54,admin.,married,tertiary,no,184,no,no,unknown,5,may,673,2,-1,0,unknown,yes

In [3]:
data.drop(['default','contact','pdays','poutcome'],axis='columns',inplace=True)

In [4]:
inputs = data.drop('loan',axis='columns')
target = data['loan'].map({'yes':1,'no':0})

In [5]:
inputs

,age,job,marital,education,balance,housing,day,month,duration,campaign,previous,deposit
0,59,admin.,married,secondary,2343,yes,5,may,1042,1,0,yes
1,56,admin.,married,secondary,45,no,5,may,1467,1,0,yes
2,41,technician,married,secondary,1270,yes,5,may,1389,1,0,yes
3,55,services,married,secondary,2476,yes,5,may,579,1,0,yes
4,54,admin.,married,tertiary,184,no,5,may,673,2,0,yes
...,...,...,...,...,...,...,...,...,...,...,...,...
11157,33,blue-collar,single,primary,1,yes,20,apr,257,1,0,no
11158,39,services,married,secondary,733,no,16,jun,83,4,0,no
11159,32,technician,single,secondary,29,no,19,aug,156,2,0,no
11160,43,technician,married,secondary,0,no,8,may,9,2,5,no
11161,34,technician,married,secondary,0,no,9,jul,628,1,0,no

In [6]:
target

0        0
1        0
2        0
3        0
4        0
        ..
11157    0
11158    0
11159    0
11160    1
11161    0
Name: loan, Length: 11162, dtype: int64

In [7]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [8]:
age_ = LabelEncoder()
job_ = LabelEncoder()
marital_= LabelEncoder()
education_= LabelEncoder()	
balance_= LabelEncoder()	
housing_= LabelEncoder()	
month_= LabelEncoder()		
deposit_= LabelEncoder()

In [9]:
inputs['age_'] = age_.fit_transform(inputs['age'])
inputs['job_'] = job_.fit_transform(inputs['job'])
inputs['marital_'] = marital_.fit_transform(inputs['marital'])
inputs['education_'] = education_.fit_transform(inputs['education'])
inputs['balance_'] = balance_.fit_transform(inputs['balance'])
inputs['housing_'] = housing_.fit_transform(inputs['housing'])
inputs['month_'] = month_.fit_transform(inputs['month'])
inputs['deposit_'] = deposit_.fit_transform(inputs['deposit'])

In [10]:
input_n = inputs.drop(['age','job','marital','education','balance','housing','month','deposit'],axis='columns')

In [11]:
x_train,x_test,y_train,y_test = train_test_split(input_n,target,test_size=0.2)

In [12]:
from sklearn import tree
model = tree.DecisionTreeClassifier()

In [13]:
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [14]:
model.score(x_test,y_test)

0.780564263322884

In [15]:
x_test

,day,duration,campaign,previous,age_,job_,marital_,education_,balance_,housing_,month_,deposit_
6966,5,269,1,0,16,0,1,2,1202,1,3,0
9828,22,119,1,0,27,0,1,1,3435,0,8,0
3928,6,415,1,3,8,9,2,1,1485,1,11,1
8501,20,216,2,0,35,4,1,2,499,0,1,0
9820,18,19,4,6,8,0,2,1,565,1,8,0
...,...,...,...,...,...,...,...,...,...,...,...,...
4534,5,1240,1,0,18,1,1,0,801,1,8,1
5560,19,64,7,0,32,3,1,0,3238,0,9,0
3989,17,231,1,0,63,5,1,0,1523,0,11,1
2213,2,310,1,6,28,1,1,1,1837,1,6,1
1033,20,871,3,0,34,1,1,1,3458,0,9,1

In [16]:
y_test

6966    0
9828    0
3928    0
8501    0
9820    0
       ..
4534    0
5560    0
3989    0
2213    0
1033    1
Name: loan, Length: 2233, dtype: int64

Let us now see how accurately the model predicts whether a given person with certain categories took a laon or not

In [17]:
#First person in the test data set: expected output - 0
model.predict([[30,219,5,0,11,1,1,0,1053,1,5,0]])

C:\Users\navee\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0])

In [18]:
#To remove warning let us use indexing
#First person in the test data set: expected output - 0
model.predict(x_test.iloc[[0]])

array([0])

In [19]:
#Second person in the test data set: expected output - 1
model.predict(x_test.iloc[[1]])

array([0])

This is not the output that we expected - there might be some situations where the predictions made by the model are wrong

In [20]:
#Third person in the test data set: expected output - 0
model.predict(x_test.iloc[[3]])

array([0])

In [21]:
#Fourth person in the test data set: expected output - 0
model.predict(x_test.iloc[[4]])

array([0])

Hence, we see that the predictions made by the model were right almost everytime, although there were a few exceptions